#server:
#  port: 9030
#spring:
#  application:
#    name: mc-generate-mybatis
#  datasource:
#    driver-class-name: com.mysql.jdbc.Driver
#    url: jdbc:mysql://localhost:3306/mcspcsales?charset=utf8mb4&useSSL=false&serverTimeZone=GMT%2B8
#    username: root
#    password: root
#eureka:
#  client:
#    service-url:
#      defaultZone: http://localhost:8761/eureka/,http://localhost:8762/eureka/
#  instance:
#    prefer-ip-address: true
#    instance-id: ${spring.application.name}:${spring.cloud.client.ip-address}:${server.port}
#mybatis:
#  mapper-locations: classpath:mapper/*.xml
#  type-aliases-package: com.chong.mcgeneratormybatis.entity